server:
  port: ${PORT:8080}
spring:
  application:
    name: aivleTK

  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ${MAIL_USERNAME}
  #    password: ${MAIL_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: "temp@gmail.com"
    password: "temp_password"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  datasource:
    url: jdbc:mysql://aivle08bedb.mysql.database.azure.com:3306/aivleTK?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&sslMode=REQUIRED
    username: cufblosigq
    password: beV9i3$DWXZMhLqn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
app:
  cors:
    allowed-origins: http://localhost:5173

jwt:
  secret:
    key: "aivleaivleaivleaivleaivle1234567aivleaivleaivleaivleaivle1234567"